FROM wordpress:latest

# Increase PHP upload limits
COPY uploads.ini /usr/local/etc/php/conf.d/uploads.ini

# Copy all local themes and plugins into the container
COPY wp-content /var/www/html/wp-content

# Ensure www-data (Apache) owns the content so WordPress can write to it
RUN chown -R www-data:www-data /var/www/html/wp-content
